from bardapi import Bard
import os
import time
import json

def bot(qu):
     '''
     Bayan Banat
     Ibrahim Qaisi
     '''
     os.environ['_BARD_API_KEY'] = "XQg_zA4L1UClQssWKH5vAXpRtEaKCBrs0A85lLGxkouyyEiapUgoieE9UzfWQCk-JSGynQ."

     def get_bard_answer(question):
         response = Bard().get_answer(question)
         retries = 0
         while 'content' not in response and retries < 5:
             time.sleep(1)  # Wait for 1 second before checking again
             response = Bard().get_answer(question)
             retries += 1
         return response.get('content', '')
     x = get_bard_answer(qu+"in small paragraph")
     return x
    #  x = get_bard_answer(f"give me a summary of {qu} not more than three line")
    #  y = get_bard_answer(f"give me just yes or no answer without any additional if {x} is related to mental health")
    #  z = y.split(" ")

    #  if z[0] == 'Yes.' or z[0] == 'Yes,':
    #      return x
    #  else:
    #      return "As an AI model, I must answer questions related to mental health!"

def coverstJson(li):
    js=[]
    for i in li:
        dic=dict()
        res=str(bot(i+"in less than 5 lines"))
        dic["patterns"]=i
        dic["responses"]=res
        js.append(dic)
    # Convert dictionary to JSON
    json_data = json.dumps(js)

    # Specify the file path where you want to save the JSON data
    file_path = 'output.json'

    # Save the JSON data to a file
    with open(file_path, 'w+') as json_file:
        json_file.write(json_data)
    return "Done"

def merge():
    bayan=["The last of my emotions belong to my pets. Today my dad said he might get rid of them tomorrow. If that does happen I might dig hole in the ground with a paper that says here lays my emotions. R.I.P. I practically have no emotions left and I came to the realization about this not being normal by comparing my reaction to certain situations to my family's. What's wrong with me?","Me and my girlfriend just broke up. She said she loves me but is not in love anymore. This came out of nowhere. We seemed so happy together.It all started when she went to Missouri to visit her family. The first week she was there she was fine then once she went to this one sisterâ€™s house everything changed. That's when she told me she loved me but was not in love with me anymore. I thought maybe it was just because she missed her family and she just wanted to be home because she told me that she could not leave them again.Then she told me to come to her in Missouri. So that's what I did. I quit my job I dropped everything, said goodbye to my family in Florida and drove 15 straight hours to be with her.Once I got there everything was fine again. Â She apologized for everything and said she didn't mean any of it then we were good for about a week. Then she went back to saying she didnâ€™t love me anymore and had no feelings for me.The only thing that really gets me and makes me not want to accept this is that now she is pregnant. This wasnâ€™t an accident. We were trying to get pregnant, so all this is hard to accept. I love her so much. I have never been bad to her. I've treated her the best I can. I wanted her to be my wife. I was going to propose to her when she got back. Now I'm losing my family and my mind. I don't know what to do.","Now I have anger and trust issues. How can I treat this and fix myself?","I have been with this guy on and off for 8 years. At first, we used to do things together and our sex life was ok. Then things started to change, we'd break up and reconnect, and he cheated on me numerous times.  We've also had two beautiful baby girls during this time. Now we argue and he says I am not affectionate at all or I don't know how to please a man, when I work part-time, take care of a 2 year old and a 5 month old and cook. Sometimes he cooks, but he also spends a lot of time on the internet. In addition, I have 2 boys and he has 1 son. I feel somewhere I have lost something. It's not that I donâ€™t care, I truly love this guy, but I'm just tired of being the one who is always being judged. Please, I am in need of a Christian counselor to help us because I really need to speak to someone.","My son claims that hes been having extremely violent thoughts and dreams. Not violent like he's hurting someone, but violent thoughts like horrible things happening to his loved ones. He explained one of his dreams the other day and it was so violent it was sickening. It was far beyond anything in a horror movie, he says he can't help these thoughts they just pop up. Please help!","Whenever I leave my girlfriend I get panic attacks. I'm taking medications to control them, but I'm thinking of moving in with her since I get so anxious.","I need to get on base to see my doctor. My ID card was in my wallet which was stolen. Im unable to reach my husband at this time. He is only one who can take me on base in order to get a new ID so I can continue to see doctor. Is there anything I can do?","Ive known my boyfriend for several years. We were friends for a long time. In 2013 we started a relationship, and he even asked me to move in with him since I lived out of state. I planned to move in with him in 2014 after I finished school and he found a job. However, during this time we had a few arguments and broke up with each other for a short period of time. We decided later to make it work. Shortly after, I found out that I was pregnant. I wanted to tell him during his next visit. However, he never came to see me and instead asked me for money. After I gave him money, he quit answering my phone calls and texts. Soon after, I experienced a miscarriage. I texted him about what had happened, and he didnâ€™t seem to care. I was extremely hurt by this. I still decided to move back as I had originally planned. He helped me with the move and replaced the money I had lent him. During this time, I asked if he wanted to be in this relationship because I needed to know. Although he says he did, I hardly ever see him. He never got a job, which was in the original plan.  After that, we both started seeing other people for a short amount of time but once again got back together. Once we got back together, I cut all ties with the former relationship I had been in. I thought he had too. But I found out that he did not attempt to do as I did and was still talking with another woman. In fact, he had even sent inappropriate pictures to her. When I confronted him about this, he wasnâ€™t apologetic. He said that he only did it to get even with me and was actually mad at me for looking through his phone. He even closed his car window on my finger and tried to throw me out of his car. I donâ€™t know what to do.","I am going through a divorce from a narcissistic sociopath who left me for another woman after mentally and emotionally abusing me for 11 years. I have moved to a different state and after giving up my successful business am working as a server at a restaurant. Iâ€™m coping as best as I can. Is it normal and healthy to not adapt as quickly and be as strong as I think I should be? I am astounded at his cruelty and how much he doesn't care, as well as most other people in my life. I feel like I don't exist to anyone anymore as there is no contact from anyone who I thought cared about me. My brother just said no to lending me a few hundred dollars for me to live on. I am losing faith in humanity itself.","I've been married for 3 years and I have two kids. During my 3-years married, my husband cheated on me twice.  The second time really got to me and at my lowest I hurt him back. We aren't communicating as well as I would like. What do I do?","I have been with my husband for almost 7 years. We got engaged a little after 5 years of being together. I had always been clear that I wanted to get married and I sadly would drop hints about how i wanted him to propose. When he did propose it was during a random vacation that I had planned. I was happy but I couldn't help feeling disappointed too.I had told him numerous times before that I wanted him to do it in front of my friends and family. I know it sounds dumb to be upset but I couldn't help how I was feeling.We are now married but the wedding and ring were also far from what I wanted and it wasn't due to lack of funds.  I know this is all material and the marriage is the most important thing but I cant help but get jealous and envious every time I see someone get a proposal or wedding that I had wanted.I cant help my anger because I know we only get one proposal and one wedding. What I wanted will never happen.I have been working on my feelings for the past year and half to get over it. I try to focus on our marriage but every time I see someone have the best proposals and weddings I get upset.I know it is selfish and I know its petty but I just can't control it. It's ruining our relationship because I constantly think about it. Plus, I get mad at him for small things because I am trying to hide the fact that I am so disappointed. Why can't I move on?","What can I do to stop grieving my motherâ€™s death?  When I am awake I just cry every day. I don't have anyone to talk to. I need help; I am still cry over her.  Will I ever stop crying? Itâ€™s been 3 years.","I'm having issues with my relative. The police never believe the experiences I have been through because I am only a kid.Â I've even had trouble trying to reach a therapist because I said I wanted to get an adult to help me. Could you please give me advice?","About 3 years ago or so I was skinny, but I was still ugly. I really do want to change that but I've tried 3 times. Now can I try but don't stop. At school I get bullied about my weight and my ugliness and I have been bullied my whole life that I believe them.How can I stop thinking about them and don't let it get in my head? My parents said I don't weight that much but, they do think I am fat but, they tell me I am not. I told my parents that I need to go to a therapist, but they think I am fine and I think they don't want to deal with it.","A few nights ago I talked to this girl I know about my self esteem issues for the first time. We talked for hours and she told me time and again that I was a great guy. She told me I was attractive, and have a great personality, etc. I really started to feel better about myself by the time I woke up the next morning.Now, though, I can't stop thinking about her, but I leave to go back to college in a few days and I go to school 4 hours away from her. So now I feel constantly depressed because even if I told her how I felt it wouldn't matter. I feel helpless and I don't know what to do.","She cried because she lost all trust in me. Now I feel disgusting and like my heart just got stabbed, what do I do?","When having sex I think of other men and want other men all day long. Been married 3 years, together 14. What do you think?","We make love once per month. Is it normal?","In this argument my friends are all against me so I'm wondering if I'm exaggerating my feelings. I feel like I'm being attacked and that is making me blow things out of proportion and taking the role of the victim, when in reality I'm the one being unreasonable and I am simply annoying my reasonable friends. Or are they really being insensitive and not respecting me in our friendship?","I am always down and out. Could this be postpartum depression?","I am married to a beautiful lady. I love my wife with all my heart. We have 3 boys and I have a daughter from a previous marriage. We also have 3 grandchildren.Now this event is tearing us apart. I want our family to be together and happy. It was a mistake from so long ago. My wife wants to leave and I don't want that to happen I love her so much. Please help me save my marriage. Even my 3 boys want us to work it out. They love us both and want our family together. Please give me some advice or hope. Sincerely heart broken.","We do communicate but one of us has trouble accepting what the other person says. How can I fix things?","My wife and I are newly married, about 2 months. We've had some issues surrounding sex, particularly her lack of libido. She's on an anxiety medication, of which diminished libido is a side effect, but I think our issue is also partly one of a lack of intimacy/romance centered around my hectic schedule. Our sex life has suffered as a result.Tonight she made a genuine effort to let me know she wanted sex, which is a big deal. Once things started, she had the most obviously fake orgasm I've ever encountered. I was honest with her about why, and told her that the most important thing to me in sex was knowing that she was legitimately enjoying it. She responded angrily with a complete denial of the faking. I don't know how to broach this subject and have an honest conversation. I think she will continue to lie to me about faking it which will cause our sex life to spiral further. Please help.","I'm always told I'm not good enough or trying hard enough. I put 100% in to every thing. I'm worn out, I've worked on all of my family relationships, I'm doing great in school, I'm kind to those in need and otherwise. I stick to my religious beliefs and leave room for mistakes and learn from others so I don't have to make as many and the ones I do I learn from. Somehow it's still not good enough and nothing I do works. Nothing has changed, and I feel hopeless. Any suggestions or ideas?","I'm always told I'm not good enough or trying hard enough. I put 100% in to every thing. I'm worn out, I've worked on all of my family relationships, I'm doing great in school, I'm kind to those in need and otherwise. I stick to my religious beliefs and leave room for mistakes and learn from others so I don't have to make as many and the ones I do I learn from. Somehow it's still not good enough and nothing I do works. Nothing has changed, and I feel hopeless. Any suggestions or ideas?","He's been losing feelings and he doesn't know why. I love him very very much. He sometimes thinks I'm obsessed when I'm not at all. I give him his space and I make sure he's okay but  sometimes I think if me and him saw each other more it would be better?I truly want me and him to get better, it's kind of hard not to stress about it, because the love of my life is losing feelings which is a sad feeling. He's a great guy! I just don't know why he's been losing feelings towards me. He's starting to put less effort in talking to me.At this point I'll do anything to just make us better as a couple. I tried talking to him but he doesn't like talking about it much. Advice on what to do?","I want a secure relationship with someone that wants to be with me and who will actually put effort into it.I seem to gravitate toward unavailable men and those that want intimacy and no relationship. I let men dictate and control me because they accuse me of being controlling. I let men emotionally abuse me and I am at their beck and call.I am not comfortable being alone or doing anything by myself. I feel I need the security of someone being around just to survive. I know what I'm doing wrong and I do it anyway just hoping things will change. How do I stop this behavior and thought process?","I regret ever hurting her and they mean the world to me. But it feels like nothing I do seem to work.I'll always love them no matter what and when I'm with them nothing else matters. I love them more then anything. I don't want another guy raising my kids.","I have dog obsession disorder and I am having problems with my girlfriend because I am placing more importance to my two dogs over her. How do I get over this problem and prioritize my girlfriend over my two dogs?","I find myself lying about small everyday things that there is really no need to lie about. How do I figure out what triggers me to do this? And how do I help overcome this problem? I would like to become more honest and open no matter the situation.","I've been like this ever since I was in school; back then I transferred to another school. Now I'm thinking about changing my job.","I keep hearing I am attractive from people around me, and I think I believe it. But I have low confidence regarding approaching girls I like.","We have been fighting a lot and have 3 kids but we both want to stay together. I need some help to save our family.","I'm currently dating someone else and I really like him. But I love and miss my ex so much. What do I do?","I feel like I have to be promiscuous in order to keep people around? It started after I got raped by my ex-boyfriend.","We kissed and he grabbed my boobs and we exchanged some texts and a few calls. It went on for about 8 months. Just when we were all together and our spouses were out of the room. Once I met him for lunch to tell him that we needed to stop. We ended up kissing after lunch and then I sent him a few more texts that day telling him I was serious and that was the end of it. His wife (my good friend) saw us kiss once and told my husband. I told him a couple of things then and we got over it.A year later she told him a couple of other things. Same story. It's been about 3 years since. They are now divorced and my husband and I have been happy. A few weeks ago the wife called me and said that her now ex told her more stuff we did. I decided to just tell my husband everything. We are trying to work things out. But he is having a really hard time believing that he knows all of it. How can I help him believe me?","Cheating is something unacceptable for me but because we have two daughters I decided not to break up the family.However, now I am struggling to forget and forgive what happened. I feel like I cannot trust him. Without trust, I cannot stay in this relationship. On the other hand, I do not want my children to get hurt. I'm not sure how to move forward?","I feel that I need to end my present relationship. He lives three hours away and likes the reassurance of having someone to talk to multiple times per day and seeing me once or twice a month.  I want someone who is more present and more of a life companion.Lately, he has had a very busy work schedule and I have only seen him a few times in the last 6 weeks. I told him that I can't continue in this way because I constantly feel frustrated and angry and that he is not making the relationship enough of a priority. I also feel it is keeping me from possibly finding the relationship I want.We have been together 7 years. The problem is that I panic and experience anxiety and depression thinking of him with someone else and then thinking I will never meet someone I like. We have gone through this cycle already 4-5 times and I feel it is unhealthy to stay in it, but my aversion to the anxiety and depression I experience upon separation always leads me to reconcile."]
    Ibrahim=[
    "How would you describe your overall emotional well-being?",
    "Do you feel generally satisfied with your life?",
    "Have you experienced any recent changes in your sleep patterns?",
    "Do you often find it difficult to concentrate or stay focused?",
    "Have you noticed a loss of interest or pleasure in activities you used to enjoy?",
    "Do you frequently experience feelings of sadness or hopelessness?",
    "Have you ever had thoughts of self-harm or suicide?",
    "Are you easily irritable or prone to sudden mood swings?",
    "How do you typically cope with stress in your life?",
    "Have you sought professional help for mental health concerns in the past?",
    "Do you have a support system of friends or family members you can rely on?",
    "Are you currently taking any medications for mental health conditions?",
    "Have you experienced any traumatic events in your life?",
    "How would you rate your self-esteem and self-confidence?",
    "Do you engage in any self-care activities on a regular basis?",
    "Are you satisfied with your personal relationships?",
    "Have you noticed any changes in your appetite or weight recently?",
    "How often do you experience feelings of anxiety or panic?",
    "Are you able to identify and express your emotions effectively?",
    "Do you have a history of substance abuse or addiction?",
    "Are you currently experiencing any phobias or irrational fears?",
    "Have you ever been diagnosed with a specific mental health disorder?",
    "How does stress typically manifest in your body (e.g., headaches, muscle tension)?",
    "Do you engage in any mindfulness or relaxation practices?",
    "How do you handle conflicts or disagreements with others?",
    "Have you experienced any significant life transitions or changes recently?",
    "Are you able to set healthy boundaries in your personal and professional life?",
    "Do you have a healthy work-life balance?",
    "Are you generally satisfied with your body image and physical appearance?",
    "Do you have a history of sleep disorders or insomnia?",
    "How would you describe your ability to adapt to change?",
    "Do you frequently experience racing thoughts or a mind that won't calm down?",
    "Have you ever been the victim of bullying or harassment?",
    "Are you currently in a romantic relationship? If so, how is it affecting your mental health?",
    "How would you describe your level of social support and connection?",
    "Do you engage in regular physical exercise or movement?",
    "How do you feel about your current financial situation?",
    "Have you experienced any recent losses or bereavement?",
    "Are you able to assert yourself and communicate your needs effectively?",
    "Do you often feel overwhelmed or overloaded with responsibilities?",
    "Have you ever experienced dissociation or a feeling of being disconnected from reality?",
    "How do you typically handle setbacks or failures?",
    "Do you engage in any creative outlets or hobbies?",
    "Are you able to forgive yourself and others for past mistakes?",
    "How would you rate your problem-solving and decision-making skills?",
    "Have you ever been diagnosed with a personality disorder?",
    "Are you able to express your needs and emotions without feeling guilty?",
    "How do you define success in your life?",
    "Do you often compare yourself to others and feel inadequate?",
    "Have you ever been a victim of domestic violence or abuse?",
    "Are you able to practice self-compassion and self-care?",
    "How would you describe your overall level of optimism?",
    "Do you have a history of self-sabotaging behaviors?",
    "Are you satisfied with your current career or professional path?",
    "How would you rate your ability to manage time and prioritize tasks?",
    "Have you ever experienced hallucinations or unusual sensory perceptions?",
    "Do you have a history of eating disorders or disordered eating habits?",
    "How do you typically handle criticism or negative feedback?",
    "Are you able to find meaning and purpose in your life?",
    "Have you ever had difficulty trusting others or forming close relationships?",
    "Do you often experience feelings of guilt or shame?",
    "How would you rate your problem-solving and decision-making skills?",
    "Are you able to express your needs and emotions without feeling guilty?",
    "How do you define success in your life?",
    "Do you often compare yourself to others and feel inadequate?",
    "Have you ever been a victim of domestic violence or abuse?",
    "Are you able to practice self-compassion and self-care?",
    "How would you describe your overall level of optimism?",
    "Do you have a history of self-sabotaging behaviors?",
    "Are you satisfied with your current career or professional path?",
    "How would you rate your ability to manage time and prioritize tasks?",
    "Have you ever experienced hallucinations or unusual sensory perceptions?",
    "Do you have a history of eating disorders or disordered eating habits?",
    "How do you typically handle criticism or negative feedback?",
    "Are you able to find meaning and purpose in your life?",
    "Have you ever had difficulty trusting others or forming close relationships?",
    "Do you often experience feelings of guilt or shame?",
    "How would you rate your body awareness and connection?",
    "Are you able to set healthy boundaries with others?",
    "Have you ever struggled with body dysmorphia or body image issues?",
    "Do you often feel a sense of emptiness or loneliness?",
    "Are you able to identify and communicate your needs effectively?",
    "How would you rate your level of emotional intelligence?",
    "Do you engage in any practices to enhance your self-awareness?",
    "Have you ever been diagnosed with an anxiety disorder?",
    "Are you able to effectively manage your stress levels?",
    "How do you typically handle conflicts within your relationships?",
    "Are you satisfied with your current living situation?",
    "Do you often experience feelings of resentment or bitterness?",
    "Have you ever struggled with addictive behaviors (e.g., gambling, shopping)?",
    "Are you able to practice gratitude and focus on the positive aspects of life?",
    "How would you rate your ability to set and achieve goals?",
    "Do you engage in any form of social activism or volunteer work?",
    "Have you ever been diagnosed with a mood disorder (e.g., depression, bipolar disorder)?",
    "Are you able to forgive yourself and others for past mistakes?",
    "How do you typically handle rejection or failure?",
    "Are you satisfied with your level of intimacy and connection in relationships?",
    "Do you often experience feelings of worthlessness or low self-esteem?",
    "Have you ever had difficulty managing your anger or impulsivity?",
    "Are you able to establish and maintain healthy boundaries in relationships?",
    "How would you rate your ability to practice self-compassion?",
    "Do you often experience intrusive thoughts or worries?",
    "Are you satisfied with your current level of social support?",
    "Have you ever been diagnosed with a psychotic disorder (e.g., schizophrenia)?",
    "Are you able to effectively communicate your emotions to others?",
    "How do you handle setbacks or disappointments in your life?",
    "Do you engage in any form of creative expression (e.g., writing, painting)?",
    "Have you ever experienced a traumatic event or post-traumatic stress disorder (PTSD)?",
    "Are you able to maintain healthy boundaries with technology and social media?",
    "How would you rate your ability to regulate your emotions?",
    "Do you often experience feelings of jealousy or envy?",
    "Are you satisfied with your current level of self-care?",
    "Have you ever struggled with body dysmorphic disorder (BDD)?",
    "Are you able to practice mindfulness and be present in the moment?",
    "How do you handle changes and uncertainty in your life?",
    "Do you often feel overwhelmed by your responsibilities?",
    "Are you able to express your needs and assert yourself in relationships?",
    "How would you rate your ability to cope with difficult emotions?",
    "Do you engage in any form of spirituality or religious practices?",
    "Have you ever been diagnosed with an eating disorder?",
    "Are you satisfied with your level of self-confidence?",
    "Have you ever experienced episodes of mania or hypomania?",
    "Are you able to maintain a healthy work-life balance?",
    "How do you typically handle feelings of loneliness or isolation?",
    "Do you often experience symptoms of burnout or chronic stress?",
    "Are you able to practice effective problem-solving in your daily life?",
    "How would you rate your ability to manage your time and prioritize tasks?",
    "Have you ever been diagnosed with attention deficit hyperactivity disorder (ADHD)?",
    "Are you satisfied with your current level of assertiveness?",
    "Do you often experience feelings of guilt or self-blame?",
    "Are you able to establish and maintain healthy boundaries with others?",
    "How do you handle criticism or rejection from others?",
    "Do you engage in any form of relaxation techniques (e.g., meditation, deep breathing)?",
    "Have you ever struggled with addiction or substance abuse?",
    "Are you able to practice self-acceptance and embrace your flaws?",
    "How would you rate your ability to handle conflicts within your family?",
    "Are you satisfied with your current level of financial well-being?",
    "Have you ever been diagnosed with a personality disorder (e.g., borderline personality disorder)?",
    "Are you able to effectively communicate your needs and expectations in relationships?",
    "How do you typically handle overwhelming emotions?",
    "Do you often experience feelings of fear or anxiety in social situations?",
    "Are you satisfied with your current level of personal growth and development?",
    "Have you ever struggled with obsessive-compulsive disorder (OCD)?",
    "Are you able to find meaning and purpose in your work or daily activities?",
    "How would you rate your ability to cope with major life changes?",
    "Do you often feel a sense of disconnection or detachment from reality?",
    "Are you satisfied with your current level of academic or intellectual stimulation?",
    "Have you ever been diagnosed with a specific phobia?",
    "Are you able to practice forgiveness and let go of grudges?",
    "How do you handle setbacks or failures in your academic or professional life?",
    "Do you often experience feelings of self-doubt or imposter syndrome?",
    "Are you satisfied with your current level of social engagement and participation?",
    "Have you ever struggled with compulsive behaviors (e.g., gambling, shopping)?",
    "Are you able to practice self-reflection and learn from your experiences?",
    "How would you rate your ability to manage conflicts within friendships?",
    "Do you often experience feelings of overwhelm or sensory overload?",
    "Are you satisfied with your current level of physical health and well-being?",
    "Have you ever been diagnosed with an impulse control disorder (e.g., kleptomania)?",
    "Are you able to maintain healthy boundaries with work-related stress?",
    "How do you typically handle feelings of envy or jealousy?",
    "Do you engage in any form of creative or artistic expression as a coping mechanism?",
    "Have you ever struggled with a dissociative disorder (e.g., dissociative identity disorder)?",
    "Are you able to practice self-care and prioritize your own needs?",
    "How would you rate your ability to manage conflicts within your community?",
    "Do you often experience feelings of existential or philosophical pondering?",
    "Are you satisfied with your current level of recreational or leisure activities?",
    "Have you ever been diagnosed with an adjustment disorder?",
    "Are you able to effectively communicate your emotions and needs to healthcare providers?",
    "How do you handle feelings of overwhelm or burnout in your professional life?",
    "Do you often experience feelings of irritability or anger?",
    "Are you satisfied with your current level of involvement in hobbies or interests?",
    "Have you ever struggled with hoarding disorder?",
    "Are you able to practice self-compassion and treat yourself with kindness?",
    "How would you rate your ability to manage conflicts within your community or society?",
    "Do you often experience feelings of disorientation or confusion?",
    "Are you satisfied with your current level of spiritual or religious engagement?",
    "Have you ever been diagnosed with a cognitive disorder (e.g., dementia)?",
    "Are you able to maintain a healthy balance between work and personal life?",
    "How do you typically handle feelings of jealousy or competition?",
    "Do you engage in any form of physical activity or exercise for mental well-being?",
]
    mohamad=["Do you feel overwhelmed by stress?",
    "Have you experienced changes in your sleep patterns?",
    "Do you often feel sad or down?",
    "Are you able to concentrate on tasks?",
    "Have you lost interest in activities you used to enjoy?",
    "Do you have frequent mood swings?",
    "Have you noticed changes in your appetite or weight?",
    "Do you feel anxious or excessively worried?",
    "Have you had thoughts of self-harm or suicide?",
    "Do you have trouble making decisions?",
    "Are you easily irritable or angered?",
    "Are you able to cope with everyday stressors?",
    "Have you sought professional help for your mental health?",
    "Do you engage in regular exercise or physical activity?",
    "Have you noticed changes in your energy levels?",
    "Do you use any coping mechanisms, such as meditation or journaling?",
    "Are you satisfied with your relationships?",
    "Have you experienced any traumatic events in your life?",
    "Do you have a positive outlook on life?",
    "Have you noticed any changes in your motivation levels?",
    "Are you able to set and achieve goals?",
    "Do you engage in activities that bring you joy?",
    "Have you experienced any symptoms of panic attacks?",
    "Do you feel socially isolated or lonely?",
    "Have you sought social support for your mental health?",
    "Are you able to express your emotions effectively?",
    "Do you have healthy coping mechanisms for stress?",
    "Have you noticed changes in your self-esteem?",
    "Do you feel in control of your life?",
    "Have you experienced feelings of hopelessness?",
    "Do you have trouble falling asleep or staying asleep?",
    "Have you lost interest in personal hygiene or self-care?",
    "Do you have racing thoughts or difficulty quieting your mind?",
    "Have you experienced changes in your appetite, such as overeating or undereating?",
    "Do you engage in excessive or compulsive behaviors?",
    "Have you experienced memory problems or difficulty concentrating?",
    "Do you have recurring negative thoughts or beliefs about yourself?",
    "Have you withdrawn from social activities or isolated yourself from others?",
    "Do you feel a sense of worthlessness or guilt?",
    "Have you had difficulty managing your anger or irritability?",
    "Do you engage in risky or self-destructive behaviors?",
    "Have you experienced physical symptoms without a clear medical cause?",
    "Do you feel disconnected from reality or have trouble distinguishing what's real?",
    "Have you had difficulty in maintaining a stable job or education?",
    "Do you have intrusive thoughts or images that cause distress?",
    "Have you experienced a significant decrease in your motivation or drive?",
    "Do you struggle with body image issues or have an unhealthy relationship with food?",
    "Have you experienced paranoia or feelings of persecution?",
    "Do you have difficulty trusting others or forming close relationships?",
    "Have you lost a sense of purpose or meaning in your life?",
    "Do you experience overwhelming fear or anxiety in certain situations?",
    "Do you engage in self-sabotaging behaviors or have a fear of success?",
    "Have you had difficulty in managing your time or staying organized?",
    "Do you have a history of substance abuse or addiction?",
    "Have you experienced hallucinations or heard voices?"]
    firas=[
    "I've been feeling really down lately. I don't know what to do.",
    "I haven't thought about it. Do you think it would help?",
    "I've always been hesitant to seek help. I'm worried about being judged or misunderstood.",
    "That's reassuring to hear. How do I find a mental health professional who would be a good fit for me?",
    "I've been feeling extremely anxious lately. I don't know how to calm down.",
    "I've tried deep breathing, but it doesn't seem to help much.",
    "I've thought about therapy, but I'm worried it won't make a difference.",
    "That makes sense. How do I find an anxiety specialist?",
    "I've been struggling with my self-esteem lately. I constantly feel inadequate and not good enough.",
    "I haven't tried that. How do I start?",
    "I'm afraid to open up about my struggles. What if people judge me?",
    "That's reassuring. How long does it typically take to improve self-esteem?",
    "I've been feeling overwhelmed and stressed out lately. I don't know how to cope with everything on my plate.",
    "I find it hard to relax and switch off my mind. Any tips for managing stress?",
    "I'm worried about burning out. How do I prevent it?",
    "I've been having trouble sleeping. I constantly toss and turn throughout the night.",
    "I've tried a few things, but nothing seems to work. I'm always wide awake when I try to sleep.",
    "I'll give those techniques a try. What if I still can't sleep?",
    "I've been feeling a lack of motivation and interest in things I used to enjoy. I don't know what's wrong with me.",
    "I haven't spoken to anyone yet. I'm not sure if it's severe enough to seek help.",
    "I'm hesitant, but I'll consider reaching out. How do I find a mental health professional?",
    "I'm feeling really stressed about an upcoming exam. I don't know how to manage the pressure.",
    "I have, but I still feel overwhelmed.",
    "I've been experiencing frequent panic attacks. It's really scary, and I don't know how to control them.",
    "I haven't tried those techniques. I'll give them a shot.",
    "I recently experienced a significant loss, and I'm having trouble coping with the grief. It feels overwhelming.",
    "I'll look into finding a grief counselor. Thank you for the suggestion.",
    "I feel anxious ,I need help or advice to deal with the anxiety I'm experiencing.",
    "I feel worried ,I need help or advice to cope with the worry I'm feeling.",
    "I feel depressed, I need help or advice to deal with the depression I'm experiencing.",
    "How do I get rid of confused thinking",
    "I have poor ability to focus",
    "How do I get rid of intense fears?",
    "How do I get rid of anxiety and excessive guilt",
    "I feel disconnected from friends and usual activities",
    "How do I get rid of thinking isolation from reality",
    "I do not have the ability to face daily problems or pressures",
    "I have trouble understanding situations and people",
    "I have major changes in my eating habits",
    "I feel unhappy, I need help or advice to overcome the unhappiness I'm feeling.",
    "I have sleep problems, I need help or advice to address the sleep problems I'm having.",
    "I experience appetite changes, I need help or advice to manage the changes in my appetite that I'm experiencing.",
    "I feel withdrawn,I need help or advice to overcome the withdrawal I'm feeling.",
    "I feel guilty, I need help or advice to cope with the guilt I'm feeling.",
    "I feel worthless, I need help or advice to deal with the feeling of worthlessness I'm experiencing.",
    "I have changes in behavior, I need help or advice to manage the changes in my behavior that I'm experiencing.",
]
    sajeda=["hello how are you today can you help me",
   "I have a problem sleeping",
   "I suffer from constant headaches and a feeling of exhaustion",
   "I suffer from anxiety",
   "Tell me how to get rid of stress",
   "My day is very bad",
   "How do I overcome my shyness",
   "How do I get rid of depression",
   "How do I know if I have depression?",
   "How can I overcome a headache",
   "How can I overcome fatigue",
   "What is the difference between psychotherapy and medication",
   "How can I get rid of overthinking",
   "What are the characteristics of a narcissistic person?",
   "I feel tired how do I get rid of this feeling",
   "Tell me about something that helps you relax",
   "Tell me about the causes of depression",
   "How can psychotherapy help me improve my life?",
   "How do I overcome the pressure always affects my mental state",
   "How do I get rid of bad people from my life",
   ]
    bayan2 = ["I had a head injury a few years ago and my mind races all the time. I have trouble sleeping and have a lot of anxiety. Every medicine I have been on my body rejects; I get sick to my stomach and get blisters in my mouth. How can I calm my self down? I'm a wreck.","I want a secure relationship with someone that wants to be with me and who will actually put effort into it.I seem to gravitate toward unavailable men and those that want intimacy and no relationship. I let men dictate and control me because they accuse me of being controlling. I let men emotionally abuse me and I am at their beck and call.I am not comfortable being alone or doing anything by myself. I feel I need the security of someone being around just to survive. I know what I'm doing wrong and I do it anyway just hoping things will change. How do I stop this behavior and thought process?","I easily recognize this but have no control over it and need suggestions for managing my anger.","It takes me a long time to fall asleep; Iâ€™d estimate about two hours. I often have nightmares, starting with being eaten by a monster, and I often wake up frightened and unable to breathe.I believe I started losing sleep after breaking up with a girlfriend of 8 years. Also, my fatherâ€™s business went bankrupt and my mother has a chronic condition. I was under a lot of stress, and life lost meaning.After improving my life and developing a habit of running and exercise to release stress, my symptoms improved. However in the past couple months, I started losing sleep again and having nightmares without warning. How can I solve this issue?","What do you do when a therapist and a parent drugs a child and makes up lies in order to stop the other parent's custody visitation?","They're calling me names like hypocrite and a baby even when they act in the same manner as I do. I'm tired of being called names. What should I do?","Cheating is something unacceptable for me but because we have two daughters I decided not to break up the family.However, now I am struggling to forget and forgive what happened. I feel like I cannot trust him. Without trust, I cannot stay in this relationship. On the other hand, I do not want my children to get hurt. I'm not sure how to move forward?","I have a lot of issues going on right now. First of all, I have a lot of trouble sleeping at times, while other nights I sleep too much and still feel quite tired. Iâ€™m also noticing increased irritability and experiencing anxiety attacks that last for hours. Is there something wrong with me and if so what should I do?","I have no sex drive due to medical issues. Iâ€™ve shut down completely and closed everyone out. Iâ€™ve even told my husband that I wanted a divorce since thatâ€™s what I thought he wanted to hear. However, it devastated me when I learned he's seeing someone else.Iâ€™ve since told him that I wanted to work things out but heâ€™s not sure I actually mean it. He thinks the only reason I want him back is because Iâ€™m jealous.  How do I show him Iâ€™m serious?","I have a lot of issues going on right now. First of all, I have a lot of trouble sleeping at times, while other nights I sleep too much and still feel quite tired. Iâ€™m also noticing increased irritability and experiencing anxiety attacks that last for hours. Is there something wrong with me and if so what should I do?","My sibling and I constantly argue and can't seem to find common ground. How can we resolve our conflicts and build a healthier sibling relationship?","I'm facing financial difficulties and can't keep up with bills and expenses. What resources or strategies can I use to manage my finances more effectively and overcome this challenging situation?","I recently lost a loved one, and the grief is consuming me. How can I navigate the grieving process and find ways to honor their memory?","I've been experiencing low self-esteem and a negative body image. What steps can I take to improve my self-confidence and develop a healthier relationship with my body?","I'm in a toxic friendship, but I'm unsure how to end it without causing further harm. How can I gracefully distance myself and prioritize my well-being?","My brother just broke up with his girlfriend. While they were dating for the past two years, her son spent the weekends with me and my mother. Now she doesn't think her son should have any interaction with us. How should we approach the situation? Is she doing the right thing for her child?","My wife and mother are having tense disagreements. In the past, they've had minor differences. For example, my wife would complain to me my mother is too overbearing; my mother would complain my wife is lazy.However, its intensified lately. I think the cause is my wife talked back to her once. Now, any little disagreement is magnified, leading to major disagreements. What can I do?","I'm planning to have baby, so I have to quit smoking - but it's hard. Sometimes it's not a physical need, it's mental.I cannot help myself from thinking about smoking. What can I do to get rid of this addiction?","I have secrets in my mind, and I don't know what to do with them. I don't want to tell my wife and mom because I don't want to hurt them. But I'm not sure how long that I can keep the secret to myself.What should I do? It's becoming annoying and making me anxious. Help me out","I am extremely possessive in my relationships and this is hurting my friendships. How can I fix my underlying issues?","I've been in a long-term relationship, but lately, my partner seems distant and uninterested. How can I communicate my concerns and work on improving our connection?","I'm a single parent and struggling to balance work and family responsibilities. What strategies can I use to create a healthy work-life balance and still be there for my children?","My parents recently got divorced, and I feel torn between them. How can I manage the conflict and maintain a good relationship with both of them?","I suspect that a close friend is struggling with addiction, but they haven't opened up about it. How can I approach the topic sensitively and offer support?","I've been feeling overwhelmed with stress and anxiety lately. What coping mechanisms or self-care practices can I incorporate into my daily routine to improve my mental well-being?","My best friend betrayed my trust. How can I rebuild the friendship or move on from the situation?","Im feeling overwhelmed with financial problems. What strategies can I use to manage my finances and reduce stress?","I recently moved to a new city and I'm finding it hard to make friends. How can I build a social network and feel connected?","I'm dealing with a toxic friendship. How can I establish healthy boundaries and maintain my well-being?","I'm experiencing a loss of motivation and interest in my hobbies. How can I regain my passion and find joy again?","I'm facing a major life transition I just changed my careers. How can I adapt to the changes and navigate this new chapter?","How can I set healthy boundaries with others to protect my well-being?","What are some effective stress management techniques I can implement?","I recently lost my job and I'm feeling hopeless. How can I stay motivated and find new opportunities?","My parents are going through a divorce and it's affecting me deeply. How can I cope with the emotional turmoil?","I'm having difficulties in my romantic relationship. What steps can I take to improve communication and resolve conflicts?","I'm struggling with a decision and I don't know what to do. How can I gain clarity and make the right choice?","How can I deal with feelings of loneliness and isolation?","I'm struggling with low self-esteem. What are some techniques to build self-confidence?","How do I cope with the loss of a loved one?","What are some ways to manage and reduce anxiety in daily life?","How can I improve my communication skills in personal relationships?","I'm going through a major life transition. How do I navigate this change and maintain a positive outlook?","I've been experiencing sleep problems and it's affecting my overall well-being. Any tips for improving sleep quality and establishing a bedtime routine?","I feel overwhelmed and stressed with my workload. How can I manage my tasks effectively?","I'm having trouble sleeping at night. What are some strategies to improve my sleep quality?","I'm a perfectionist and it's causing a lot of stress and self-criticism. How can I overcome perfectionism and learn to embrace imperfection?","I'm a caregiver for a loved one and feeling burnt out. Any suggestions for self-care and preventing caregiver fatigue?","I often feel overwhelmed by my emotions and have trouble regulating them. Any strategies for managing and expressing my emotions in a healthy way?","I'm dealing with a major life change and feeling scared of the unknown. How can I embrace change and find courage to move forward?","I'm having difficulty maintaining healthy relationships. How can I improve my communication skills and build stronger connections with others?","I'm struggling with low self-esteem and negative self-talk. Any advice on building self-confidence and developing a positive mindset?","I have a hard time forgiving others who have hurt me in the past. How can I let go of resentment and move forward?","I've been feeling unmotivated and uninspired lately. Any tips for finding motivation and reigniting my passion?","I'm constantly worrying about the future and it's affecting my daily life. How can I manage my anxiety and find peace of mind?","I've been experiencing symptoms of burnout and exhaustion. Any strategies for preventing burnout and practicing self-care?","I have a friend who is struggling with addiction. How can I support them on their journey to recovery?","I'm going through a major life transition and feeling lost. How can I navigate this period of change and find a sense of direction?","I'm dealing with body image issues and low self-confidence. Any suggestions for developing a positive body image and self-acceptance?","I feel lonely and isolated. How can I build a supportive social network and make meaningful connections?","I'm a parent and feeling guilty about not spending enough time with my children. How can I balance parenting and other responsibilities?","I've been experiencing panic attacks and don't know how to manage them. Any tips for coping with panic disorder?","I have trouble asserting myself and saying no to others. How can I develop better boundaries and prioritize my own needs?","I'm struggling with a recent breakup and finding it hard to move on. Any advice on healing a broken heart?","I'm feeling overwhelmed with work and constantly stressed. How can I achieve a better work-life balance?","I'm a student facing exam stress and pressure. How can I manage my time effectively and reduce exam anxiety?","I've been dealing with procrastination and lack of motivation. Any strategies for increasing productivity and staying focused?","I've been experiencing relationship issues with my partner. How can we improve communication and strengthen our bond?","I have a friend who seems to be struggling with depression. How can I support them and encourage them to seek help?","I'm feeling stuck in my career and unsure about my future. Any guidance on finding my passion and making meaningful career choices?","I recently lost a loved one, and I'm struggling with grief. How can I cope with the loss and start the healing process?","My parents don't understand me and constantly put pressure on me. How can I communicate with them effectively and set boundaries?","I'm having trouble sleeping and often experience nightmares. Any suggestions for improving my sleep quality?","How can I improve my self-esteem and feel more confident in social situations?","I'm constantly feeling anxious and overwhelmed. What can I do to manage my anxiety?","My wife just last week said she wants a divorce and it's all sudden. I understand that marriages have their ups and downs but I don't understand why she can't tell me why she wants a divorce. Should I fight for my family (daughter and wife)?","I loved him more than anything. He passed away on our anniversary which was also the day I was going to apply for our apartment. I'm not handling it well. I moved to a new town and started a new life but nothing helps.","I did some horrible sexual things as a kid and I regret everything. Can someone help me cope with myself? Can someone help me remember my past?","I have been with a guy for 4 years,  he's a great guy and we also have a son together. The problem is that I'm in love with a guy that I've been talking to for about 2 years but I've never met him in person. Honestly I'm bored with the relationship I have with the first guy and he makes want to go after the second guy, I don't know how to tell him that. What should I do?","My boyfriend can't get over my promiscuous past. He says he loves me  but says the thought of my past is disgusting and a sexual distraction. He says he should have had more sex with different people. I don't know how to handle this.","What do I do if I have been feeling like I could never be with anyone because no one would want me. Or I couldn't have many friends because of who I am. It's strange I want to be loved but I'd hate to be because I always lose.","What makes my step child, an 8 year old boy, choke my daughter, a 6 year old girl? This has been going on for 4 years. The boy tells my daughter not to tell on him. He knows it's wrong; we have did time out, spanking, taking away toys, and sitting on the wall. I am afraid for my daughters safety!","My coworkers are making false statements about me to the boss, saying I have mood swings. They have no proof to back it up. Can my employer make me see a therapist of their choice?","I'm in a state of depression right now. Who can I talk to? I've been sick in a lot of pain and crying. Don't know where to turn.","I'm a 40 year old male and having erection problems. Still have the desire for a woman. Awfully frustrated. Any suggestions? My Doc doesn't want to discuss it.","My husband cheated on me and it hurt me very bad. It was a time when my health was poor. I'm have a hard time moving on.","I've been abused emotionally all of my life and for some reason I keep getting with men that I let emotionally abused me.How can I stop it? I know the mistakes that I've made in my life. I'm having a really hard time getting back on my feet. Can you help me please?","I feel like I would be more comfortable as a girl even though I still like girls. I think I'm like a girl stuck in a guy body. I imagine myself as a girl too. I think this more because my friends say that if I was a girl I would be a hot looking one. And I don't care about having boobs or anything. I just feel like the way that I do act will make more sense if I was a girl.","I've have lived for sometime with depression but things have gotten a lot better, but why is it so hard to get over anxiety and social isolation?","I have a child with my baby mother. She works I take care of our young son. She says she is not cheating I have not found anything but she always putting me down, telling me to get out and telling me she doesn't love me, but then the next day after our fight she says she does. I'm having a hard time because before our child she said she was raped by a family member but she never went to the hospital or the cops. Now me and my family don't talk. She's always telling me I'm annoying and just belittles me. Nothing I do is right.She says I work you watch the baby. On her days off she never cooks or cleans. I have no friends or family and a couple months ago she was confiding to some guy, but says he's not any thing to her. What do I do? I don't want to leave.","Or how to send him somewhere that can help him, something like The Baker Act.","In particular during family gatherings (such as funerals), where there are different customs.","I don't know what's wrong with me. At times I can be really happy, excited, I'll talk fast, and I want to do things. But lately I've been staying up way later and sleeping too much. I don't hang out with friends, I don't really have them. I feel nothing, worthless. I want to do nothing, I have no interest in anything. All I usually do is stay in my room. I want to be happy, I want to be nice. What's wrong with me?","I'm worried I should see a therapist due to past events and current mental status. I'm just so unsure of how to ask my doctor about seeing someone.","I feel like my time is going too fast","I'm worried I should see a therapist due to past events and current mental status. I'm just so unsure of how to ask my doctor about seeing someone.","My last relationships have ended horribly. They just up and abandoned me. One of them I have never gotten closure with over it, leaving me emotionally wrecked. I know something's wrong with me but I don't know how to even start trying to better myself.I get into these depressed like states whenever anyone I care about is too busy to be with me. I know that I shouldn't act like that because people are genuinely busy, but I feel like they're doing it just because they don't want to be around me.","I haven't uttered one word to my boyfriend in days. Now I'm over it and don't know how to approach the situation?","I've been with my boyfriend over 3 years. He cheated on me and the woman is now pregnant. He is physically and mentally abusive towards me. I have attempted to talk with him in order to resolve our issues; however, he never wants to talk and often blames me for everything.Im always there when he needs my help. He tells me although I help him doesnâ€™t mean that I am a good person. He always discredits me as a woman and itâ€™s hurtful. I spend most day crying and feeling lonely. I am unhappy and unsure of what I need to do.","I started dating a guy I met online. He told me that he registered sex offender but he didn't do anything. He took a plea to always register as sex offender and he did two years. That was more than two decades ago. Nothing on his record since.I always believe the past should be left in past. But my roommates, their family and my son are unforgiving. Should I forgive this man that I'm falling in love with or should I dump him? If I stay with him I will never see my family and granddaughter again."]
    aseel=["How are you"]
    team=[bayan,Ibrahim,mohamad,firas,sajeda,aseel,bayan2]
    all=[]
    for i in team:
      all+=i
    return all

if __name__=="__main__":
    # a="in less than 5 lines"
    li=merge()
    print(coverstJson(li))
